### ISSUE TITLE
Questions about gcn model

### ISSUE THREAD

**Issue by CaoZPLQ** [StefanBloemheuvel/GCNTimeseriesRegression#2]
When I execute "python main_gcn.py network1 main 1" when I go to main_gcn.py line 121: "conv1 = layers.Conv1D(filters=32, kernel_size=125, strides=2,  activation=activation_func,  kernel_regularizer=regularizers.l2(reg_const), name='conv1')(wav_input)", **ValueError: Input 0 of layer conv1 is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received:  [None, 39, 1000, 3]** is displayed. Is this a problem with my Keras version? My environment tensorflow=2.2.0,keras=2.3.1, or other problems? Thank you

**Comment by StefanBloemheuvel** [comment]
Hello!

For me it seems to work, so it has to be dependencies indeed! I will update the readme but also answer here :)

geopy==2.2.0
keras==2.8.0
networkx==2.7.1
numba==0.56.2
numpy==1.22.3
scikit-learn==1.0.2
scipy==1.8.0
sklearn==0.0
spektral==1.1.0
tensorflow==2.8.0

**Comment by CaoZPLQ** [comment]
Thank you very much! It works.
